### ISSUE TITLE
All Contest page

### ISSUE THREAD

**Issue by albseb511** [masai-oss/execode#101]
- ~~Redux~~
- ~~connect component to store~~
- ~~fetch API~~
- ~~fill dummy data~~
- ~~make api with redux thunk~~

**Santhi:**
- Dynamic routing for View Submissions button
- API testing

**Comment by albseb511** [comment]
Fixed:

Needs testing with API.

https://github.com/masai-oss/execode/commit/6884399ac0e1b9d1000f5f07ea55a3372917cffb

**Comment by santhisrikh** [comment]
Working on it ,assign it to me.
