### ISSUE TITLE
get all challages of particular contest backend route needs correction

### ISSUE THREAD

**Issue by santhisrikh** [masai-oss/execode#107]
![Screenshot from 2020-01-20 19-16-07](https://user-images.githubusercontent.com/52741412/72731689-30fc0500-3bba-11ea-800d-716470c83559.png)
Instead of getting different challenges only one challenge got repeated.

**Comment by albseb511** [comment]
confirm if the data in db is correct? or is it a query problem?

**Comment by sachinkapalidigi** [comment]
Having the same issue with leader board route and submission route
