### ISSUE TITLE
logout user

### ISSUE THREAD

**Issue by albseb511** [masai-oss/execode#142]
- logout
- disable jwt token on logout

**Comment by Warewolf96** [comment]
The only way you can disable jwt token is wither by blacklisting it ot deleting it from the frontend. What do you suggest we do for this? I can make a table for blacklisted tokens and check every auth if the token belongs to that list.

Suggestions @albseb511 ?

**Comment by albseb511** [comment]
Keep an expiration time in the JWT token?
After decryption, check if time is expired.
This logic can be reused in session extension also

**Comment by Warewolf96** [comment]
@albseb511  This is already being done, I added role in JWT as well. expiration time set in JWT is of 1 day and 5 seconds, let me know if you want me to change that to lower time limit.

**Comment by albseb511** [comment]
There was a bug noted on the expiration of time, can you have a look at https://github.com/masai-oss/execode/issues/49

and see if its resolved?

**Comment by Warewolf96** [comment]
Resolved!
