### ISSUE TITLE
User Login Page : Login.jsx

### ISSUE THREAD

**Issue by krishna7860** [masai-oss/execode#32]
* Component for Login Page 
* File : routes/login.jsx 

##### Mockup
![Screenshot from 2020-01-03 23-20-07](https://user-images.githubusercontent.com/31980947/71739791-790fed80-2e80-11ea-98ef-cf747165fd97.png)

**Comment by krishna7860** [comment]
Assign to Krishna Kant Sharma

**Comment by Warewolf96** [comment]
PR #34
