### ISSUE TITLE
TodayContest.jsx 

### ISSUE THREAD

**Issue by mihirlaldas** [masai-oss/execode#36]
@Warewolf96 @amanvats Please assign to mihir
component - TodayContest
File location -  routes/Dashboard/User/Contest/TodayContest.jsx

![TodayContest](https://user-images.githubusercontent.com/38202855/71820240-94fbd500-30b4-11ea-8a2f-e74b5ec293bb.png)

**Comment by Warewolf96** [comment]
PR #44
