### ISSUE TITLE
Create Contest

### ISSUE THREAD

**Issue by sachinkapalidigi** [masai-oss/execode#42]
## Contest

​

POST `/contest/<contest_name>`

​

Required Headers - `Authorization: JWT <access_token>`

​

#### REQUEST

​

BODY

```json

{

            "contest_id":"INTEGER",

            "contest_name":"STRING",

            "start_date":"DATETIME",

            "end_date":"DATETIME",

            "end_time":"INTEGER",

            "details":"STRING",

            "show_leader_board":"BOOLEAN",

            "challenges_ids":["INTEGER","INTEGER","INTEGER"],

            "action":" "

}

```

​

#### RESPONSE

​

Success (Status Code - 201)

```json

{

           "comment":"Successfully created Contest"

 

​

}

```
![Screenshot from 2020-01-07 14-17-58](https://user-images.githubusercontent.com/31788669/71881590-9979c980-3158-11ea-9c4e-c983a9fc6ac6.png)
![Screenshot from 2020-01-07 14-18-05](https://user-images.githubusercontent.com/31788669/71881591-9979c980-3158-11ea-9c23-c0c07faf31d9.png)

​

**Comment by Warewolf96** [comment]
PR #43
